### ISSUE TITLE
Static builpback scores F on Mozilla Observatory

### ISSUE THREAD

**Issue by s-toussaint** [cloudfoundry/staticfile-buildpack#155]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
   "api_version": "2.133.0",
   "osbapi_version": "2.14",
   "routing_endpoint": "https://api.run.pivotal.io/routing"
}

What version of the buildpack you are using?
Default buildpack version as determined when pushed to Pivotal Web Service

If you were attempting to accomplish a task, what was it you were attempting to do?
I deployed an Angular application using StaticFile ( with pushstate: enabled and force_https: true) and then scan my application with Mozilla Observatory.
Note: I am creating this issue as recommended from Pivotal forum https://community.pivotal.io/s/question/0D50e00005dIJN7CAO/hii-have-an-angular-application-that-i-deploy-to-pws-using-a-staticfile-when-running-the-security-scan-from-the-mozilla-observatory-site-i-go-an-f-score-id-like-to-know-how-i-can-increase-this-scoreregardsstephane

What did you expect to happen?
I expected to get an 'A' score.

What was the actual behavior?
I got an 'F' score.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by kardolus** [comment]
Thanks @s-toussaint - looking into this.

**Comment by kardolus** [comment]
@s-toussaint A lot of these headers are user provided. For example, my score went up to a 'D' by adding these two headers to a simple app: 
```
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' https://code.jquery.com;" />
    <meta http-equiv="Content-Security-Policy" content="X-XSS-Protection: 1; mode=block" />
```
We could think about providing headers by default for our users, or perhaps making it easier to add headers somehow. Or provide better documentation on this to help our users. Those are more product questions though. ^ @sclevine @shanks3012

**Comment by ryanmoran** [comment]
Hi @s-toussaint!

We spent a bit of time looking into what would be needed to get an A+ from the Mozilla Observatory scanner. We discovered that there are a handful of headers that can be set using existing functionality in the buildpack so that the application is considered secure by the scanner. We've included all of those settings in a [fixture in the repository](https://github.com/cloudfoundry/staticfile-buildpack/tree/74b94ab183019467b3ea31202d0b961650a4969f/fixtures/secure_app).

Each of these settings is application specific and would need to be something that users opt-in to setting for their application. This means that we won't be able to provide default values for these settings in the buildpack itself, but can provide an example of how to use the buildpack in a manner that will result in a secure static site.

Check out the example secure app. We hope that this helps answer how you might secure your application.
