### ISSUE TITLE
precise support available

### ISSUE THREAD

**Issue by wenlock** [cloudfoundry/staticfile-buildpack#32]
Hi, I was trying this out on HDP 1.1, and seems like my docker images are precise.  Is there any reason we wouldn't want to add precise to the Vagrantfile to get some precise vendor images?

**Comment by flavorjones** [comment]
Hi @wenlock,

Thanks for asking this question.

I'm curious about your particular use case, as currently the supported rootfses are `lucid64` (which is based on Lucid) and `cflinuxfs2` (which is based on Trusty).

I don't know much about HDP. Can you explain a bit more about what you're doing, why you're using Docker instead of Warden/Garden, and why your Docker image is based on Precise?

I'm only asking because it's a bit of a work for us to add another rootfs to our build and test pipelines, and to maintain functionality for something that's not supported by CF today.

Thanks for any information you can provide. Cheers!

-mike

**Comment by flavorjones** [comment]
@wenlock Just bumping this issue. If you have a moment, can you answer some of my questions above?

If I don't hear back in another day or so, I'll go ahead and close this issue.

**Comment by wenlock** [comment]
Yep , were simply using out of the box helion dev platform 1.1, which sets up with docker and precise is in our dc .  I expect that it will be updated to newer is' sin the future but for now that's what they provide.  If it helps I've been using ours since I made the pull without issues.
