### ISSUE TITLE
Default configuration outputs redundant access logs (mostly duplicate of RTR logs)

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/staticfile-buildpack#68]
By default, the static buildpack configure nginx to [produce access logs on ephemeral FS](https://github.com/cloudfoundry/staticfile-buildpack/blob/97c4e23babc455845d7a8f08c221ee5f312693a1/conf/nginx.conf#L9), and then [streams them to stdout](https://github.com/cloudfoundry/staticfile-buildpack/blob/97c4e23babc455845d7a8f08c221ee5f312693a1/bin/boot.sh#L32-L33)

```
2016-03-14T14:53:36.32+0100 [RTR/0]      OUT test-status.mysite.org - [14/03/2016:13:53:36 +0000] "GET /hello.txt HTTP/1.1" 200 0 6 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0" 192.168.26.30:51519 x_forwarded_for:"10.[...]" x_forwarded_proto:"http" vcap_request_id:cb89cf0e-2adc-4e14-5c7c-06c824d683c6 response_time:0.002860578 app_id:f55fd562-a491-45f1-ac3e-38aa7f73952a
2016-03-14T14:53:37.06+0100 [APP/0]      OUT ==> /home/vcap/app/nginx/logs/access.log <==
2016-03-14T14:53:37.06+0100 [APP/0]      OUT 10.[...] - - - [14/Mar/2016:13:53:36 +0000] "GET /hello.txt HTTP/1.1" 200 6
```

The information is roughly the same as what provided by default by the gorouter, with mostly format change, with the polluting trace from the ```cat``` command listing the ephemeral FS log path.

It does not seem a very useful default to have, as this mostly appear as duplicated logs, and would slightly impact performance without real benefits by default. 

More over, it might be worth checking that the default log is indeed rotated and does not end up filling up the ephemeral FS max quota until the garden FS limit is reached and the app will be crashed by garden.

https://www.nginx.com/resources/wiki/start/topics/examples/logrotation/

Suggesting to turn off the nginx access log file by default.

**Comment by davidjahn** [comment]
Hi @gberche-orange , thank you very much for your suggestion to turn off nginx logging by default.

Regarding the container's file system max size being exceeded, I do not believe that this is a problem because the two log files are in fact just [named pipes](https://github.com/cloudfoundry/staticfile-buildpack/blob/97c4e23babc455845d7a8f08c221ee5f312693a1/bin/boot.sh#L29-L30) created with `mkfifo`, and do not persist any data to disk.

However, you are correct that many of the nginx log messages are duplicated by the router log messages, and it might be good decision to turn off nginx logging by default. A story in pivotal tracker has been created automatically, and we will discuss the issue further at our next planning meeting. Thanks again!

**Comment by davidjahn** [comment]
Hi @gberche-orange , we discussed this issue this morning, and decided that for now we will leave logging turned on by default. There are two reasons for this:

1. Although the most common log messaged (e.g., a successful HTTP request) for nginx are duplicated by gorouter logging, there are possible nginx logging messages (for example, errors) that the gorouter will not duplicate.
1. It is possible for the user to turn off logging entirely by adding a custom `nginx.conf` to an app's root folder.

We don't feel that the gain in performance from turning off logging will outweigh the loss of debugging data for the user.

I am closing the issue for now, but please feel free to comment if you have any additional comments to add.
