### ISSUE TITLE
Avoid use of ephemeral FS for nginx error logs: nginx can output logs to sdterr

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/staticfile-buildpack#69]
Currently nginx error logs are written to ephemeral FS and then streamed using the cat command.

Also, it might be worth checking that the error  log is indeed rotated and does not end up filling up the ephemeral FS max quota until the garden FS limit is reached and the app will be crashed by garden.

It seems nginx supports outputing them directly to stderr instead of going to ephemeral FS, see http://nginx.org/en/docs/ngx_core_module.html#error_log which would make this more optimal and safe.

``
The first parameter defines a file that will store the log. The special value stderr selects the standard error file.
``

**Comment by davidjahn** [comment]
Hi @gberche-orange , thank you for your comments. Currently nginx error logs in the static file buildpack are written to a (named pipe)[https://github.com/cloudfoundry/staticfile-buildpack/blob/97c4e23babc455845d7a8f08c221ee5f312693a1/bin/boot.sh#L29-L30] created with `mkfifo`. Named pipes do not persist information to disk, and there should be no possibility of reaching the FS disk quota writing to these pipes.

It is true that nginx has an option to write directly to `/dev/stderr`, however unfortunately due to permission issues in the garden container, nginx is not able to write directly to either `/dev/stderr` or `/dev/stdout`. This is why we chose to create named pipes, and redirect their output using `cat`.

**Comment by gberche-orange** [comment]
Thanks @davidjahn for your answer and correcting me (sorry I missed the mkfifo call). 

I guess removing the named pipe would remove the buffering (apparently [close to 64k on Linux](http://unix.stackexchange.com/questions/11946/how-big-is-the-pipe-buffer) and "race condition" between nginx producing logs and cat consumming.

Is there a related ticket in garden-linux or guardian ? Seems docker is also suffering from the same limitation and is being addressed as part of https://github.com/docker/docker/issues/6880#issuecomment-147087387

**Comment by jtarchie** [comment]
@gberche-orange did we resolve your original issue? You bring up another point about buffering above, which I am not sure I follow in relation to the `mkfifo`. If you are using a custom `nginx.conf`, you should have access to the named pipes, too.

**Comment by gberche-orange** [comment]
@jtarchie yes thanks, I'm closing the original issue w.r.t. writes to the ephemeral FS.

Besides, I'm still interested to hear whether the garden-linux or guardian is aware of the /dev/stderr limitation that the static buildpack met with nginx, and whether something is planned to improve it.
