### ISSUE TITLE
MIME types for fonts

### ISSUE THREAD

**Issue by kyrylkov** [cloudfoundry/staticfile-buildpack#87]
Will you accept a pull request to add MIME types for fonts?

**Comment by RochesterinNYC** [comment]
What is the use case that this would fulfill?

**Comment by kyrylkov** [comment]
Enabling `Expires` and `Cache-Control` for local font without modifying
default `mime.types`

Sergiy Kyrylkov
linkd.in/1s2YFJw

**Comment by kyrylkov** [comment]
@RochesterinNYC  Enabling `Expires` and `Cache-Control` for local font without modifying
default `mime.types`

**Comment by athornton2012** [comment]
Just to clarify, right now in order to enable a `Expires` setting for a font type, you would have to specify something like:
```
# Expires map
map $sent_http_content_type $expires {
    default                off;
    text/html              epoch;
    font/ttf               max;
    font/opentype          max;
}
```
as well as providing your own `mime.types` file (because the font mime.types do not exist in our default buildpack provided `mime.types` file).

And you would like to include font types in the existing default `mime.types` file provided by the buildpack, so that users no longer have to include their own `mime.types` file for this use case?

**Comment by kyrylkov** [comment]
@athornton2012 exactly

**Comment by athornton2012** [comment]
@kyrylkov Yes, we would take a PR that includes specs.

**Comment by sesmith177** [comment]
closing based on @athornton2012's comment

**Comment by kyrylkov** [comment]
@athornton2012 https://github.com/cloudfoundry/staticfile-buildpack/pull/88
