### ISSUE TITLE
Breaking change in v1.4.0 - removed bin/boot.sh

### ISSUE THREAD

**Issue by jakub-gawlas** [cloudfoundry/staticfile-buildpack#99]
In version v1.4.0 script `bin/boot.sh` has been removed, it was used by me for run instances. What is a replacement for it? 

btw. Maybe more accurate was update version to 2.0.0? Because it was breaking change.

Thanks ;)

**Comment by sclevine** [comment]
Hi @jakub-gawlas, thanks for the report!

The buildpack contract is explained most clearly in our instructions for writing custom buildpacks: https://docs.cloudfoundry.org/buildpacks/custom.html#custom-buildpacks

As with most software, we make no guarantees about internal implementation details of the buildpack changing from one release to the next. You rely on the behavior of anything besides `/bin/compile`, `/bin/detect`, and `/bin/release` at your own risk. Furthermore, we only guarantee that these scripts maintain compatibility with Cloud Foundry and documented buildpack features. For instance, we may change the resulting droplet, or the patch-level version of buildpack dependencies without notice, so long as it doesn't interfere with the staging and launch of existing applications that use the buildpack.

We do not plan to introduce an equivalent script to `/bin/boot.sh` in the future.

**Comment by flavorjones** [comment]
@sclevine I'm curious what drove the decision to move files into internal Go vars?

**Comment by sclevine** [comment]
I suspect this was initially done to simplify the implementation -- it's easier to read a variable compared to a file. Maybe @dgodd can chime in.

I didn't question it because:
1. It discourages users from providing a custom nginx.conf, compared to recently-added Staticfile directives like `location_include`.
2. The Go template logic in those variables is executed during staging, and is not valid in a custom nginx.conf file.

**Comment by sclevine** [comment]
Closing as the question has been addressed.
